### ISSUE TITLE
used for my z17minis

### ISSUE THREAD

**Issue by gaows20** [HighwayStar/android_device_nubia_msm8976-common#1]
Hello ,HighwayStar
<br />i see this project for nubia msms8976,can i port  for my z17minis use your repositories.?thanks.   Tg:xiaoxiao6208

**Comment by HighwayStar** [comment]
Sure, it only need to test kernel for nx589j an do nx589j device that will use msm8976-common repo

**Comment by gaows20** [comment]
thanks 。thanks。
